- hosts: localhost
  become: yes
  gather_facts: false

  tasks:
    ## Tasks file for EC2 launch ##
    - name: Launch EC2 Instance
      ec2:
        image: "{{ image_id }}"
        instance_type: "{{ type }}"
        region: "{{ region }}"
        wait: yes
        count: 1
        state: present
        vpc_subnet_id: "{{ pubsubnet_result.subnet.id }}"
        assign_public_ip: yes
        group_id: "{{ security_group_results.group_id }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        instance_tags:
          Name: "{{ instance_name }}"
